### ISSUE TITLE
Fortnite won't launch it says Connection game timed out?(I'm on Mac)

### ISSUE THREAD

**Issue by Melowald** [RareDevs/Rare#337] opened 2023-12-13 21:11 UTC
I installed the windows version of Fortnite on raregui3
[Rare_Launcher_Fortnite_23-12-13--15-48.log](https://github.com/RareDevs/Rare/files/13665756/Rare_Launcher_Fortnite_23-12-13--15-48.log)

**Comment by loathingKernel** [comment] 2023-12-13 21:55
Give this testing build a try https://github.com/loathingKernel/Rare/releases, it might have been solved indirectly

**Comment by Melowald** [comment] 2023-12-14 07:17
> Give this testing build a try https://github.com/loathingKernel/Rare/releases, it might have been solved indirectly. I do not have a Mac testing platform.

It didn't work unfortunately

**Comment by loathingKernel** [comment] 2023-12-14 10:56
Closing this as duplicate

**Comment by loathingKernel** [comment] 2023-12-14 10:56
Duplicate of https://github.com/RareDevs/Rare/issues/314

**Closed by loathingKernel** 2023-12-14 10:56 UTC
Labels: bug
